### ISSUE TITLE
mutual information errors

### ISSUE THREAD

**Issue by gglaspell** [bostoncleek/ergodic_exploration#1]
I am very interested in your ergodic exploration especially using mutual information. I am able to successfully run the launch file in hte main branch. However, when I switch to the mi branch I am getting the following errors:

process[map_server-1]: started with pid [11512]
ERROR: cannot launch node of type [ergodic_exploration/exploration]: Cannot locate node of type [exploration] in package [ergodic_exploration]. Make sure file exists
in package path and permission is set to executable (chmod +x)
process[occupancy_grid_mi-3]: started with pid [11513]
[ERROR] [1665176036.438935400]: Tried to advertise on topic [/occupancy_grid_mi] with md5sum [3381f2d731d4076ec5c71b0759edbe4e] and datatype [nav_msgs/OccupancyGrid],
 but the topic is already advertised as md5sum [ca1a248f35f716e2b1c209d2a82e5ce3] and datatype [range_mi/MIGrid]
[ERROR] [1665176036.442042604]: Tried to advertise on topic [/occupancy_grid_mi] with md5sum [3381f2d731d4076ec5c71b0759edbe4e] and datatype [nav_msgs/OccupancyGrid],
 but the topic is already advertised as md5sum [ca1a248f35f716e2b1c209d2a82e5ce3] and datatype [range_mi/MIGrid]
[ERROR] [1665176036.454820622]: md5sum mismatch making local subscription to topic /occupancy_grid_mi.
[ERROR] [1665176036.454907401]: Subscriber expects type nav_msgs/OccupancyGrid, md5sum 3381f2d731d4076ec5c71b0759edbe4e
[ERROR] [1665176036.454934757]: Publisher provides type range_mi/MIGrid, md5sum ca1a248f35f716e2b1c209d2a82e5ce3
[ WARN] [1665176036.454963554]: couldn't register subscriber on topic [/occupancy_grid_mi]
[ERROR] [1665176036.476619335]: md5sum mismatch making local subscription to topic /occupancy_grid_mi.
[ERROR] [1665176036.476728480]: Subscriber expects type geometry_msgs/PointStamped, md5sum c63aecb41bfdfd6b7e1fac37c7cbe7bf
[ERROR] [1665176036.476758680]: Publisher provides type range_mi/MIGrid, md5sum ca1a248f35f716e2b1c209d2a82e5ce3
[ WARN] [1665176036.476783988]: couldn't register subscriber on topic [/occupancy_grid_mi]

I was hoping you had a few pointers to get this running; thanks in advance.

**Comment by bostoncleek** [comment]
This sounds like an issue with maybe the cmake file (it looks fine to me though) or something with catkin not finding the node. If you run ros launch and try to tab complete does it find the node? You can also look under the build directory in your workspace and see if it's there. Sometimes I run `catkin clean` and then rebuild when I have issues like this.

**Comment by gglaspell** [comment]
@bostoncleek You were right it was an issue with my catkin_ws. catkin clean and rebuilding resolved the issue. Thanks for the tip, I have it running now so I am going to try with my sim.
